sudo: required

services:
  - docker


env:
  global:
    - DOCKER_OPTS="docker build --build-arg"
    - basic=sumankhanal/test:basic
    - minimal=sumankhanal/test:minimal
  matrix:
    - DOCKER_VER=TeXLive-2017
    - DOCKER_VER=TeXLive-2018
    - DOCKER_VER=TeXLive-2019
  
script:
  - cd ${DOCKER_VER}
  - ${DOCKER_OPTS} scheme=scheme-basic -t ${basic} .
  - ${DOCKER_OPTS} scheme=scheme-minimal -t ${minimal} .
  - pwd
  - ls 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${basic}
  - docker push ${minimal}
