sudo: required

services:
  - docker


env:
  global:
    - DOCKER_OPTS="docker build --build-arg"
    - basic=sumankhanal/test:basic
    - minimal=sumankhanal/test:minimal
  
install:
  - cd TeXLive-2018
  - ${DOCKER_OPTS} scheme=scheme-basic -t ${basic} .
  - ${DOCKER_OPTS} scheme=scheme-minimal -t ${minimal} .
  

## A few simple / crude tests
after_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${basic}
  - docker push ${minimal}
