sudo: required

services:
  - docker


env:
  global:
    - DOCKER_OPTS="docker build --build-arg"
    - USER=sumankhanal
  matrix:
    - DOCKER_VER=TeXLive-2017
    - DOCKER_VER=TeXLive-2018
    - DOCKER_VER=TeXLive-2019
  
script:
  - cd ${DOCKER_VER}
  - REPO="$(echo ${DOCKER_VER} | tr 'A-Z' 'a-z')"
  - echo "${REPO}"
  - ${DOCKER_OPTS} scheme=scheme-basic -t ${USER}/${REPO}:basic .
  #- ${DOCKER_OPTS} scheme=scheme-minimal -t "${user}/${REPO}:minimal" .
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #- docker push ${user}/${REPO}:basic
  #- docker push ${user}/${REPO}:minimal
